### PR TITLE
Fix the Variable Explorer height so the horizontal scroll bar is shown.

### PR DESCRIPTION
**Pull request by DavidKutu**
For #4598

scroll

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]
Did you try in the interactive window too? Just want to make sure there isn't some extra space there when there wasn't before.

**Comment by IanMatthewHuff** [comment]
> Did you try in the interactive window too? Just want to make sure there isn't some extra space there when there wasn't before.

Yeah, the variableExplorer is the part that is shared between both view styles, so would need to check that as well. If the variableExplorer is now looking worse in the interactiveWindow you can consider taking a peek at setVariableViewHeight in the VariableViewPanel. That panel is the variable view specific host, if it's passing in a bit too big of a value to setVariableViewHeight, then padding that would fix sizing for just the variable view case and leave the interactive window spacing as is.

**Review by IanMatthewHuff — CHANGES_REQUESTED** [review]
I think this works, but could you try it quick with just reducing the value sent in via the height change in variableViewPanel? That would make the change specific to the new variable view.

**Comment by DavidKutu** [comment]
@IanMatthewHuff it works, but weirdly, only half of the scroll bar appears
image

**Comment by DavidKutu** [comment]
The interactive window looks the same in both solutions:

- -10 in variableViewPanel
variableViewPanel

- -10 in VariableExplorer
variableExplorer

**Review by IanMatthewHuff — APPROVED** [review]

**Comment by IanMatthewHuff** [comment]
@DavidKutu Thanks for checking. Looks good to me.

**Pull request merged**
