### PR TITLE
Update README - New kernel picker location

### PR DESCRIPTION
**Pull request by claudiaregio**
Updating README with the new text for kernel

### CODE REVIEW

**Review by joyceerhl — APPROVED** [review]
This needs to be ported to release I think?

**Review by IanMatthewHuff — APPROVED** [review]

**Comment by IanMatthewHuff** [comment]
@joyceerhl maybe point release at this point? I know that it's just a readme, but I never like messing with our branch before release.

**Comment by rchiodo** [comment]
> @joyceerhl maybe point release at this point? I know that it's just a readme, but I never like messing with our branch before release.

Is the readme.md shipped or does the marketplace pick it up from the github page?

**Comment by joyceerhl** [comment]
I believe the README is shipped (based on my experience publishing my own extensions). @DonJayamanne might be able to confirm though.

**Comment by claudiaregio** [comment]
Point release would be ok too, it's not super urgent. I'm going to update the wiki page as well so they can go out together

**Review by DonJayamanne — APPROVED** [review]

**Pull request merged**
