### PR TITLE
Adds ability for users to disable candy cursh

### PR DESCRIPTION
**Pull request by phgmacedo**
For #5387, and sorta #5056

Which was closed and locked without proper consideration. 

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [x] ~Has sufficient logging~.
-   [x] ~Has telemetry for enhancements~.
-   [x] ~Unit tests & system/integration tests are added/updated~.
-   [x] ~[Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate~.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Comment by phgmacedo** [comment]
When this PR gets merged, users can put the line `"jupyter.disableCandyCursh": true` to decrease the burden of carrying the jupyter extension by the mere fact of having the python extension. 

@DonJayamanne

**Comment by rchiodo** [comment]
I think it would be better if VS code allowed users to control their menu. This item in particular which it looks like you already commented on.

https://github.com/microsoft/vscode/issues/9285

**Comment by phgmacedo** [comment]
> I think it would be better if VS code allowed users to control their menu. This item in particular which it looks like you already commented on.
> 
> https://github.com/microsoft/vscode/issues/9285

Yeah, but what about users who *don't* want jupyter, but are forced to have it with the python extension?

**Comment by phgmacedo** [comment]
This PR would also fix [#9284 from the python extension](https://github.com/microsoft/vscode-python/issues/9284).

**Pull request closed without merging**
