### PR TITLE
Update release engine version

### PR DESCRIPTION
**Pull request by IanMatthewHuff**

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Review by amunger — APPROVED** [review]

**Comment by DonJayamanne** [comment]
i don't think we do this anymore, don't recall why, but i recall removing this option.
i think it's because we wanted users to be able to keep using vscode insiders, this action (changing engine) used to be required to force the insider release of our extension.

if still required were might want to update our release plan
https://github.com/microsoft/vscode-jupyter/issues/9423

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Already discussing in slack. I think we need it for this release as Aaron's change to New File required an update to 1.66. I've already added a note to add this as needed to the release plan.

**Comment by DonJayamanne** [comment]
> required an update to 1.66. I've already added a note to add this as needed to the release plan.

leaving as insider will also work

**Comment by rchiodo** [comment]
> leaving as insider will also work

Not as far as I know. If it says -insider, it won't load in stable, regardless of what version stable is at.

**Comment by IanMatthewHuff** [comment]
> > required an update to 1.66. I've already added a note to add this as needed to the release plan.
> 
> leaving as insider will also work

@DonJayamanne Sorry I'm a bit confused on your comment here. This updating the release branch. Just like here:
https://github.com/microsoft/vscode-jupyter/pull/9153#issuecomment-1054627430

**Comment by DonJayamanne** [comment]
aah yes thanks (couldn't remember that at all)

, please can we update the release plan, too many steps and plenty of this that can be missed (by me). im certain i would had forgotten this.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Yup. Anytime I do a release I always take notes and then update the release plan. I just wait to do it in one batch at the end. Here is the current list.

https://github.com/microsoft/vscode-jupyter/issues/9423#issuecomment-1079221603

**Pull request merged**
