### PR TITLE
Hide jupyter commands from other types of notebooks

### PR DESCRIPTION
**Pull request by DavidKutu**
For #5559

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by rchiodo — CHANGES_REQUESTED** [review]
I think we need a when clause instead

**Comment by rchiodo** [comment]
I believe we use 'Notebook' on purpose. Isn't this going to make all of those commands prefixed with 'Jupyter' instead? That seems more confusing to me.

**Comment by DavidKutu** [comment]
@rchiodo I could leave only the changes to the when clause, that's enough to fix the issue.
As of the name `Jupyter` or `Notebook`, both are going to be confusing to a group of people. I don't mind leaving one or the other.

**Review by rchiodo — APPROVED** [review]

**Comment by joyceerhl** [comment]
@rchiodo I believe Matt said in #5559 that our using 'Notebook' is confusing, because the category also indicates where the command is coming from. E.g. 'Notebook' means 'VS Code-contributed' while 'Jupyter' means 'Jupyter extension-contributed'. Since this keybinding is contributed by the Jupyter extension I think it makes sense to prefix it with 'Jupyter'. I'm also wondering if Peng/Matt have further thoughts on this.

**Comment by DonJayamanne** [comment]
@joyceerhl I don't think we should change the command group to Jupyter.
I have replied her https://github.com/microsoft/vscode-jupyter/issues/5559#issuecomment-823749451

It's something we discussed as a team (I think we even have an issue for this), I believe it came out of a QP study

**Comment by DonJayamanne** [comment]
@joyceerhl I've replied on the issues.
I don't think we should change the command group to Jupyter.
I recall discussing this with our team, as a result of a QP. Im certain we even have an issue for this (and why we changed from Jupyter to notebook).

**Comment by DavidKutu** [comment]
@joyceerhl that's a good topic to bring up in our next sync meeting. I'd vote to have everything we contribute in the  `Jupyter` group.

**Pull request merged**
