### PR TITLE
DBG Test Fails

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
For #8684

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [x] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Comment by IanMatthewHuff** [comment]
One full green run, going to remove the logging and try a second one.

**Comment by IanMatthewHuff** [comment]
Looks good on another run, just forgot to add news so adding that and up for review.

**Review by rchiodo — APPROVED** [review]

**Comment by IanMatthewHuff** [comment]
Still had a failure on the last run (after two fully green) investigating more.

**Comment by IanMatthewHuff** [comment]
Green on this run

**Comment by IanMatthewHuff** [comment]
(2x) Green. In we go.

**Pull request merged**
