### PR TITLE
Remove kernel cache as its not used

### PR DESCRIPTION
**Pull request by DonJayamanne**
We're not reading from the cache, hence removed it (fewer unnecessary disk writes).

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]
How often do we read from the list of kernelspecs? Maybe we should be using the cache?

**Comment by DonJayamanne** [comment]
@rchiodo 
Its read a lot, however we cache the promise https://github.com/microsoft/vscode-jupyter/blob/fad999e807ce74ae415cd27aeb23da9d5abe30d0/src/client/datascience/kernel-launcher/localKernelFinder.ts#L149-L149

Hence for every session, we only ever do this once per workspace.

**Review by IanMatthewHuff — APPROVED** [review]

**Comment by rchiodo** [comment]
> @rchiodo
> Its read a lot, however we cache the promise
> 
> https://github.com/microsoft/vscode-jupyter/blob/fad999e807ce74ae415cd27aeb23da9d5abe30d0/src/client/datascience/kernel-launcher/localKernelFinder.ts#L149-L149
> 
> Hence for every session, we only ever do this once per workspace.

Seems like that would be problematic when people add new environments. But I guess we have that issue with interpreters too.

**Review by DavidKutu — APPROVED** [review]

**Comment by DonJayamanne** [comment]
>  But I guess we have that issue with interpreters too.

Would be as simple as invalidating this cache when we detect new enviroments from Python extension.

**Pull request merged**
