### PR TITLE
Disable automated insider releases

### PR DESCRIPTION
**Pull request by DonJayamanne**

### CODE REVIEW

**Review by joyceerhl — APPROVED** [review]

**Review by IanMatthewHuff — APPROVED** [review]

**Review by rchiodo — COMMENTED** [review]
Why are you disabling them?

**Comment by DonJayamanne** [comment]
> Why are you disabling them?

Will discuss tomorrow.
TLDR:
* Insider version is 2021.5.xxxx & this targets VS COe 1.55.0-Insiders.
* Stable version is 2021.4.xxxx & this targets latest stable VS Code 1.55.0
* Use new VS Code 1.55.0 & this will pull down our insider build that targets 1.55.0-Insider.
* We want it to target 2021.4.xxxx

We're updating Release version to 2021.5.xxx & stopping automated uploads for now.
Tomorrw (after VS Code release) we'll enable automated updates & change engine to 1.56.0-Insiders

@rchiodo

**Comment by rchiodo** [comment]
> Use new VS Code 1.55.0 & this will pull down our insider build that targets 1.55.0-Insider.

Shouldn't this only apply for insider builds? I thought builds that target an engine with 'insider' on the end only apply to insiders builds?

**Comment by DonJayamanne** [comment]
> Shouldn't this only apply for insider builds? I thought builds that target an engine with 'insider' on the end only apply to insiders builds?

Doesn't seem to work as expected (originally anticipated)

**Pull request merged**
