### PR TITLE
Do not store kernel info in nb metadata for other VSC extension kernels

### PR DESCRIPTION
**Pull request by DonJayamanne**
For https://github.com/microsoft/vscode-jupyter/issues/4423#issuecomment-763903125

This way we don't set the kernel metadata when a non-jupyter kernel is selected.
Allowing others to update the notebook metadata without us blowing it away.

### CODE REVIEW

**Comment by rchiodo** [comment]
I'm confused. This looks like it's clearing the metadata? Don't we want to just not set it?

**Comment by DonJayamanne** [comment]
> I'm confused. This looks like it's clearing the metadata? Don't we want to just not set it?
If  you select a Jupyter kernel then we set it.
If you then select a non-jupyter kenrel we need to unset it, i.e. clear it.
This way, if users change kernels to a non-jupyter kernel (not ours), & save, then there's no custom metadata that will be set, **apart from what ever is already in there**.

If you check the method, we use call the same function to save the kernel information (but only if its our kernel).

**Comment by rchiodo** [comment]
> If you then select a non-jupyter kenrel we need to unset it, i.e. clear it.
This way, if users change kernels to a non-jupyter kernel (not ours), & save, then there's no custom metadata that will be set, **apart from what ever is already in there**.

Why wouldn't this clear the metadata set by the .NET kernel provider? Sure it won't overwrite something that's already on disk, but won't it overwrite a value in memory?

**Comment by IanMatthewHuff** [comment]
As much as I'm following this looks right to me, though I'm not 100% sure on the scenario that the C# folks are after. Is it ok that it's setting metadata to undefined as opposed to {}?

**Review by IanMatthewHuff — APPROVED** [review]

**Review by DavidKutu — APPROVED** [review]

**Review by rchiodo — CHANGES_REQUESTED** [review]
Sorry still not clear on how tis works. Maybe we should chat?

**Review by rchiodo — APPROVED** [review]

**Pull request merged**
