### PR TITLE
add button to stop RBL and continue executing

### PR DESCRIPTION
**Pull request by DavidKutu**
For #7494

This is what it looks like:
RBLContinue

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [ ] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Review by roblourens — APPROVED** [review]
This will shift the toolbar when it is right-aligned, so I'm not sure whether we want this. But, we can try it out

**Comment by roblourens** [comment]
Does the button actually show up as blue? I don't think we want that

**Comment by DavidKutu** [comment]
@roblourens those are both right, I keep forgetting the cell toolbar can change alignment. Is there a way to change the group:
image
so that it always goes to the side where it doesn't move stuff?

Also, the button does turn blue. I didn't do that, that is a default VS Code icon. Is that a bug?

**Review by DonJayamanne — APPROVED** [review]

**Comment by roblourens** [comment]
FYI I added the context key `notebookCellToolbarLocation` if you want to adopt that

**Pull request merged**
