### PR TITLE
Show variable snapshot in data viewer

### LINKED ISSUE #10942: Data Viewer: open the same variable from variable doesn't reuse Data Viewer
Testing #10915

* Click on the action "Show Variable in Data Viewer" from the variable view
* Data Viewer opened
* Click again
* It opens a new data viewer, instead of focusing on the Data Viewer again

### PR DESCRIPTION
**Pull request by sadasant**
How does this look?

Fixes #10942

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Review by rchiodo — CHANGES_REQUESTED** [review]
Doesn't this need changes to the localize.ts file too? For the translated version?

**Comment by sadasant** [comment]
@rchiodo I don't think so. Thanks to your comment I realized that this other file needed to change: https://github.com/microsoft/vscode-jupyter/pull/10967/commits/1bafecb0686fcb0f8d916dbb01f38b5b3ab0ed34

That file isn't using our `localize` function, it's using `getLocString` from `../react-common/locReactSide`, which reads from the `package.nls.json` when the localization is initialized.

**Review by rchiodo — APPROVED** [review]

**Comment by amunger** [comment]
I don't think this clarifies the action - it's not like we're going to show an old value of the variable when you click that button.
If the issue is that the variable view is static and won't keep in sync with the variable in the kernel, then I don't think this message really conveys that.
Maybe calling it a snapshot, or static view would help, but "current" doesn't imply to me that it will become stale.

**Comment by sadasant** [comment]
@amunger I like how you think! How would you phrase it? `Show variable snapshot in data viewer?`

**Comment by amunger** [comment]
> How would you phrase it? Show variable snapshot in data viewer?

yeah I would like that more

**Comment by sadasant** [comment]
@amunger pushed!

**Pull request merged**
