### PR TITLE
format readme consistently

### PR DESCRIPTION
**Pull request by jyooru**
Does not close an issue. Fixes dot point being styled as code:

Screenshot from 2021-06-15 23-38-24

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [ ] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
    Does this apply to me?
-   [x] ~~Appropriate comments and documentation strings in the code.~~
-   [x] ~~Has sufficient logging.~~
-   [x] ~~Has telemetry for enhancements.~~
-   [x] ~~Unit tests & system/integration tests are added/updated.~~
-   [x] ~~[Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.~~
-   [x] ~~[`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).~~

### CODE REVIEW

**Comment by IanMatthewHuff** [comment]
@jyooru Where is your before screenshot coming from? Bullet formatting looks ok for me on Chrome / VS Code markdown preview.

**Comment by jyooru** [comment]
Screenshot from 2021-06-18 10-05-19
It's from the extension's page in the VSCode.

Yes you are right however, it is previewing differently on the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) and inside the editor.

**Comment by jyooru** [comment]
Hi @IanMatthewHuff, this issue is still present. Any update on this PR?

**Review by DavidKutu — APPROVED** [review]

**Comment by DavidKutu** [comment]
for #6648

**Pull request merged**
