### PR TITLE
Slice data updates from QP study

### PR DESCRIPTION
**Pull request by joyceerhl**
QP feedback:
* Slice and show expanded slice controls by default
* Move refresh button from editor title menu to be next to breadcrumb
* Fix dropdown styles
* Show a placeholder slice in the input box to guide users

-   [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [ ] Title summarizes what is changing.
-   [ ] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Comment by DonJayamanne** [comment]
Can we see a screenshot of what this looks like now.

**Comment by joyceerhl** [comment]
Current screenshot (Jill and Jeffrey have signed off):

image

**Review by IanMatthewHuff — APPROVED** [review]

**Review by DonJayamanne — CHANGES_REQUESTED** [review]
> Current screenshot (Jill and Jeffrey have signed off, and this is where a customer in the QP told us he would expect to see the refresh button as well):


Shoul'dnt this be an experiment to see which is better.
Else we're setting the expectation that all icons will be on the left.
To me this is not at all discoverable, as a vscode user i'd never look for any icon next to the file name (as i know in other editors that there is nothign there).

I.e i'd prefer if we had an experiment to see which ones worked better for users. Do they use more of the one on the left or right, that seems like a better way to go than just based on a single users QP...

@jmew /cc

**Review by DonJayamanne — APPROVED** [review]
I believe @jmew has a new placement for the icon, approving based on the new placement.

**Comment by joyceerhl** [comment]
New placement: 

image

**Pull request merged**
