### PR TITLE
Point fix for duplicated data in data viewer 

### PR DESCRIPTION
**Pull request by joyceerhl**
For #

-   [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [ ] Title summarizes what is changing.
-   [ ] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by DonJayamanne — CHANGES_REQUESTED** [review]
This doesn't really tell what was fixed. 
We're not just adding tests, we're fixing a bug as well

**Comment by joyceerhl** [comment]
@DonJayamanne would a news entry help?

**Comment by rchiodo** [comment]
Maybe you should update the changelog too?

**Review by rchiodo — APPROVED** [review]

**Review by IanMatthewHuff — APPROVED** [review]

**Comment by joyceerhl** [comment]
I don't repro the smoke test failures locally FYI @DonJayamanne, still looking into them

**Review by DonJayamanne — APPROVED** [review]

**Comment by joyceerhl** [comment]
@DonJayamanne smoke tests are passing now, thanks for your fix 😊

**Pull request merged**
