### PR TITLE
Remove usage of jupyter to enumerate local kernels

### PR DESCRIPTION
**Pull request by rchiodo**
Part of the refactor work for removing kernel installation dependencies, we don't need two ways to find kernelspecs.

So I changed everything to use the kernelFinder (raw version of finding) and removed a bunch of code.

### CODE REVIEW

**Comment by IanMatthewHuff** [comment]
Wasn't this waiting until after we cut the release branch?

**Comment by rchiodo** [comment]
> Wasn't this waiting until after we cut the release branch?

Maybe? I didn't think this as risky. It's just reusing something we already have in a different spot. No change otherwise

**Review by DavidKutu — APPROVED** [review]

**Review by DonJayamanne — APPROVED** [review]
Always nice to see code getting deleted....
Woo hoo..

**Comment by DonJayamanne** [comment]
> Maybe? I didn't think this as risky. It's just reusing something we already have in a different spot. No change otherwise

Provided we test this thoroughly, I'm ok with this going in, we have the bug bash.
Also I think we do have a lot of tests now & feel fairly confident that if tests pass this should be ok (Would like to ensure we test Conda scnearios well dueing bug bash).

**Review by IanMatthewHuff — APPROVED** [review]

**Pull request merged**
