### PR TITLE
changed npm down to 8.1.0 in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Yoyokrazy**
Fixes #

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] ~Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).~
-   [x] ~Appropriate comments and documentation strings in the code.~
-   [x] ~Has sufficient logging.~
-   [x] ~Has telemetry for feature-requests.~
-   [x] ~Unit tests & system/integration tests are added/updated.~
-   [x] ~[Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.~
-   [x] ~[`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).~

### CODE REVIEW

**Comment by Yoyokrazy** [comment]
npm v8.3 when running install would change the package-lock file and was updating something, reverting to 8.1 seemed to keep everything in sync

**Comment by rchiodo** [comment]
The change it creates looks correct to me. It's updating url-parse to 1.5.10 which it needs to be. I think instead you should submit the package-lock change.

**Comment by DonJayamanne** [comment]
@rchiodo i think the change is valid, npm version 8.3 was shipped with node 16.14, but we use node 16.13 (that's what VS Code uses & I updated this recently).
& npm version that ships with node 16.13 (which is what we use) ends up shipping 8.1.
Hence this PR is correct.

**Review by DonJayamanne — APPROVED** [review]
@Yoyokrazy thanks & please add a news entry to thank your self for this contribution.

**Comment by IanMatthewHuff** [comment]
The Node / NPM version stuff is a pain at times. AFAIK Node versions can continue to update "supported" versions of npm. So you can continue to update versions of NPM with the same supported Node version. But I guess just going with "ships with" is the easiest thing to specify.

**Comment by rchiodo** [comment]
This is the total of the package lock change:

```
diff --git a/package-lock.json b/package-lock.json
index c511e148c..b14ed6bed 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -26780,7 +26780,7 @@
                 "minimist": "~1.2.0",
                 "moment": "^2.24.0",
                 "path-browserify": "^1.0.0",
-                "url-parse": "1.5.8"
+                "url-parse": "^1.5.10"
             }
         },
```
Not sure why 8.1 doesn't know to make this change, but that's correct. Our minimum version for url-parse is now 1.5.10

**Pull request closed without merging**
