### PR TITLE
renderer changes for widgets renderer + controller function change

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
For #6118 

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Comment by IanMatthewHuff** [comment]
Jupyter side of renderer changes. Again. I need to test with VSCode main after notebook/dev merges.

**Review by DavidKutu — APPROVED** [review]

**Comment by IanMatthewHuff** [comment]
@DavidKutu I reverted your review on this, just since I added in the notebook controller changes as well. Was easier to test these together in one PR.

**Review by DavidKutu — APPROVED** [review]

**Review by rchiodo — APPROVED** [review]

**Comment by IanMatthewHuff** [comment]
Manual testing results testing against main branch (ipywidget renderer):
image
Basic ipywidgets load and work + we can see the renderer loading:
image

Manual testing against main branch (client_renderer copied from vscode-notebook-renderer build into jupyter client_renderer):
image
image
Logging for renderer activated:
image

The notebookController change was just a rename, basic tests by just swapping kernels and making sure that sys.executable updated after change. Also check that I hit a BP in the new handler function name.

**Comment by IanMatthewHuff** [comment]
Manual run of our native notebook tests.
image

**Comment by IanMatthewHuff** [comment]
Test failures expected due to breaking API change. Pushing.

**Pull request merged**
