### PR TITLE
Add require to preload

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
For #6034 

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Comment by IanMatthewHuff** [comment]
Per this issue here we need this in our preloads and renderers:
https://github.com/microsoft/vscode-jupyter/issues/6034

To test this I built VS Code with the special casing to still add the loader for ipynb removed. I tested without any changes first and simple widget rendering broke trying to load the widget (as expected). Making this change here fixes that.

I wanted to loop in @DonJayamanne with a draft here as I don't consider myself a JS module loading expert. Even with no changes and the loader removed I didn't see any issues with our renderers. Per the issue here require.js was needed to support amd module loading: https://github.com/microsoft/vscode/issues/121245. However my change here (and the change in Jupyter) https://github.com/microsoft/vscode-notebook-renderers/commit/f245b5a7dee2ed61b8685b0c476ae959028fc009 moved the renderers over to loading as a Javascript module. So I don't believe that we need a change for the renderers here, but I wanted to check my understanding there. My example test file with plotly output worked fine before and after removing the loader code from vscode core.

Note: I'm prepping a PR to remove the Jupyter special case for VS Code core using the initial change from Matt.

**Review by DavidKutu — APPROVED** [review]

**Review by DonJayamanne — APPROVED** [review]

**Comment by rchiodo** [comment]
@IanMatthewHuff is there a wait on this? I wanted to try it to see if allowed the 'notebook' renderer type for plotly to work again. See bug #6334

**Comment by IanMatthewHuff** [comment]
@rchiodo Sorry just caught in the four day weekend. I need to check quick to see if the VS Code changes need to happen at the same time or not. Let me try it quick with current main. If it works there I'll push right away.
https://github.com/microsoft/vscode/pull/126939

**Comment by IanMatthewHuff** [comment]
@rchiodo I did a merge, not sure about it fixing the issue though. This just replaces vscode's loader with our loader which should be the same I think?

**Comment by rchiodo** [comment]
I'll try it out when the build comes out. The JS for plotly is failing because it's looking for the global 'require.undef'. I think adding require.js to our preloads should add that. It would explain why it works in the old webview notebook editor, it explicitly added require.js.

**Pull request merged**
