### PR TITLE
Remove run isolated script

### PR DESCRIPTION
**Pull request by DavidKutu**
For #5969, #5931

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by joyceerhl — COMMENTED** [review]
Can we not remove this script now? https://github.com/microsoft/vscode-jupyter/issues/5931

**Review by joyceerhl — COMMENTED** [review]
Is there a reason @karrtikr hasn't already merged https://github.com/microsoft/vscode-python/pull/16274? Maybe we should leave this open until trusted workspaces goes stable?

**Comment by rchiodo** [comment]
I'm rather surprised we don't need to change any code for this?

**Comment by karrtikr** [comment]
@joyceerhl Yep, that's exactly the reason. Brett asked to hold off until the June release as we also have the insiders program in VSCode stable.

**Comment by joyceerhl** [comment]
Thanks for the context @karrtikr 😊 Since the Jupyter extension does not ship insiders builds to VS Code stable, and since trusted workspaces is already enabled in VS Code Insiders, I believe we should be able to merge this now?

**Comment by karrtikr** [comment]
Yep in that case I think it's fine to merge it. As long as the trusted workspaces feature is available on VSCode insiders.

**Comment by IanMatthewHuff** [comment]
Hmm, looks like this is blowing up tests with maybe interpreter finding issues?

**Review by rchiodo — APPROVED** [review]

**Review by IanMatthewHuff — APPROVED** [review]
Provided just the one remote test failing.

**Pull request merged**
