### PR TITLE
Request access to jupyter kernel service api for getdatachimp github org

### PR DESCRIPTION
**Pull request by kmdupr33**
Request access to jupyter kernel service api for getdatachimp github org.

Fixes #

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] ~Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).~
-   [x] ~Appropriate comments and documentation strings in the code.~
-   [x] ~Has sufficient logging.~
-   [x] ~Has telemetry for feature-requests.~
-   [x] ~Unit tests & system/integration tests are added/updated.~
-   [x] ~[Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.~
-   [x] ~[`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).~

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@kmdupr33 thanks for this PR, 
As you can understand this is a proposed API and have not decided to expose this API to everyone yet, as there's still a lot of work required in stabilizing this API. As you can see from the API no one is allowed to use this (`rchiodo` is a member of the team which explains why his name is there)

Out of curiousity, why do you need access to this API? This will help us understand the needs of the API.

**Comment by kmdupr33** [comment]
>Out of curiosity, why do you need access to this API? This will help us understand the needs of the API.

I'm trying to build a tool that automatically executes code based on rules set by the data scientist. E.g., Imagine if your notebook automatically showed a bar plot depicting the percentage of missing values for all columns of a data frame if you are analyzing a data frame with a column that has more than 30% missing values.

**Comment by DonJayamanne** [comment]
> It's not a problem for me if this API is unstable. I'm happy to work with any breaking changes that occur.

Is it possibel for you to use this as is, the only problem is you'll get a message on the bottom right, thats about it.

**Comment by kmdupr33** [comment]
Hmm...are you sure? These two parts of the code suggest otherwise:

https://github.com/microsoft/vscode-jupyter/blob/7d7ddaaf41a682eafce8b1d6b91ae9d2247bb411/src/standalone/api/kernelApi.ts#L52-L57

https://github.com/microsoft/vscode-jupyter/blob/7d7ddaaf41a682eafce8b1d6b91ae9d2247bb411/src/standalone/api/api.ts#L53-L59

I would have tested this myself, but I believe the API restriction only applies for extensions running in "production."

**Comment by DonJayamanne** [comment]
@kmdupr33 Have you managed to find a work around or do you still need access.
Sorry for not getting back to you on this item.

**Comment by DonJayamanne** [comment]
Closing in favour of this https://github.com/microsoft/vscode-jupyter/pull/13662
Basically this allows anyone to review the API before using in VS Code stable.

**Pull request closed without merging**
