### PR TITLE
Update LSP packages to latest stable

### PR DESCRIPTION
**Pull request by jakebailey**
This is a version of https://github.com/microsoft/vscode-python/pull/15661 applied here.

Not sure if you want me to make an issue+news entry or not; this can go in whenever and is just a cleanup as I'm upgrading everyone now that we all require newer versions of VS Code.

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [ ] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] ~Appropriate comments and documentation strings in the code.~
-   [x] ~Has sufficient logging.~
-   [x] ~Has telemetry for enhancements.~
-   [x] ~Unit tests & system/integration tests are added/updated.~
-   [x] ~[Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.~
-   [x] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Comment by jakebailey** [comment]
Oops, I thought this would be simpler, but you're on an even older version of the LSP libs than the core extension. Guess we updated it there after the fork.

**Review by DavidKutu — APPROVED** [review]

**Review by IanMatthewHuff — APPROVED** [review]

**Comment by jakebailey** [comment]
Not sure why this is failing, but appears to be failing for basically every in-progress PR... I can merge in main whenever you'd like this to get it passing.

**Comment by DavidKutu** [comment]
I think we should take a look before merging

**Comment by DonJayamanne** [comment]
@jakebailey How crucial is this update? 
Can this go into the next release?

**Comment by jakebailey** [comment]
It can go in whenever you'd like. The core extension and pylance have already been updated to this (they were already at the version just before this and required no code change; jupyter had lagged).

**Comment by DavidKutu** [comment]
This was merged here: https://github.com/microsoft/vscode-jupyter/pull/5946
Thanks @jakebailey

**Pull request closed without merging**
