### PR TITLE
remove kernel tip

### PR DESCRIPTION
**Pull request by claudiaregio**
For https://github.com/microsoft/vscode-jupyter/issues/6016

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]
Woot! Claudia is a dev now.

**Review by joyceerhl — APPROVED** [review]

**Comment by claudiaregio** [comment]
@rchiodo let's not get carried away, @joyceerhl was kind enough to walk me through it last night :) 
She was a great teacher though so I think I could delete a popup all by my lonesome next time

**Review by DavidKutu — APPROVED** [review]

**Review by IanMatthewHuff — APPROVED** [review]

**Comment by IanMatthewHuff** [comment]
Comment: This PR makes me super happy
Reason: Putting Tip: in front of something that was clearly a tip was redundant

**Comment by joyceerhl** [comment]
@claudiaregio Feel free to merge this PR (usually we merge our own PRs once we have enough approving reviews)

**Pull request merged**
