### PR TITLE
Consume OS PRNG via executable instead of NAPI libraries

### PR DESCRIPTION
**Pull request by joyceerhl**
This is intended to replace our use of ffi-napi and ref-napi for random bytes generation on Windows. Checking this code in here for review purposes mainly.

Other things needed to complete this are: remove usage of ffi-napi and ref-napi, update randomBytes.ts to use this new executable, and update our build pipelines to include this in the packaged VSIX. In addition to setting up code signing for this executable, maybe we can upload it to blob storage and download it as part of the pipeline build process vs rebuilding it each time, since it's unlikely to change and is a standalone component.

-   [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [ ] Title summarizes what is changing.
-   [ ] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Comment by DonJayamanne** [comment]
Please can we move the source into `src` directory

**Comment by DonJayamanne** [comment]
And please can we not commit the exe into the repo. Atleast not for now. Not a fan of commiting exe into repos, or we can create a release 
against (GitHub release) and upload this there

**Review by DonJayamanne — CHANGES_REQUESTED** [review]
Blocking on moving to etc.

Not blocking due to exe, though let's upload later (this is not the final version is it?).

**Review by rchiodo — APPROVED** [review]

**Comment by joyceerhl** [comment]
> this is not the final version is it

@DonJayamanne no there'll be another PR to actually run the exe, but we need it to be codesigned first or it's going to get flagged malware 😊 This is just committing the source to our repo. I moved it under /src and deleted the exe.

**Review by DonJayamanne — APPROVED** [review]

**Comment by joyceerhl** [comment]
Updated the title to be less misleading @DonJayamanne :)

**Pull request merged**
