### PR TITLE
Merge release back into main

### PR DESCRIPTION
**Pull request by joyceerhl**
For #5398

### CODE REVIEW

**Review by DonJayamanne — APPROVED** [review]

**Comment by joyceerhl** [comment]
@rchiodo @IanMatthewHuff do we want to bump to 1.57.0-insider? This means no insider builds will go out until 1.57-insider becomes available.

**Comment by DonJayamanne** [comment]
> ant to bump to 1.57.0-insider? This means no insider builds will go out until 1.57-insider becomes available.

Why not leave it as is? I.e why do we have to bump this?

**Comment by DonJayamanne** [comment]
Lets discuss this in triage. Even I'm not sure what needs to be done here (we need to ensure users don't get this build in stable(

**Comment by joyceerhl** [comment]
@DonJayamanne pointed out that if we bump main to 1.57-insider now, we're going to have to patch the package.json locally in order to develop against main bits. I forgot about that.

**Pull request merged**
