### PR TITLE
Display notebook paths in kernel picker for remote kernels

### PR DESCRIPTION
**Pull request by DonJayamanne**
For #8175

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Comment by rchiodo** [comment]
What does it look like?

**Comment by DonJayamanne** [comment]
@rchiodo the screenshot is here https://github.com/microsoft/vscode-jupyter/issues/8175#issuecomment-962061805
Wait will upload here too so we can review & discuss
image

**Comment by rchiodo** [comment]
I think you should switch it. 

The details should be the 'last activity, 1 existing connections' or maybe not there altogether.
The descriptoin? field (thing to right of name) should be the notebook path. It's the most important piece of information.

**Review by IanMatthewHuff — APPROVED** [review]
Agree with Rich's comment on order switch, but looks good.

**Comment by DonJayamanne** [comment]
Done 
image

**Review by rchiodo — APPROVED** [review]

**Pull request merged**
