### PR TITLE
Fix electron 22 crash: update zeromq.

### PR DESCRIPTION
**Pull request by rebornix**
Prepare for the upcoming 1.77 Insiders. 1.77 ships with Electron 22, which introduces v8 memory cage. Current zeromq will crash with Electron 22. The issue was already fixed in a newer version of zeromq https://github.com/zeromq/zeromq.js/issues/514 .

More details about the v8 memory cage https://github.com/electron/electron/pull/36624

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for feature-requests.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by DonJayamanne — CHANGES_REQUESTED** [review]
Why is this required, not sure why we are updating the package apart from the fact that its a little bit more recent that the previous.
Some information (probably an issue would be great)

This way when we go bakc and look at ths history we know why things were updated.

**Review by DonJayamanne — APPROVED** [review]

**Comment by rebornix** [comment]
@DonJayamanne thanks for pointing that out. PR created in a hurry. I have updated the issue description to explain why this update is needed.

**Comment by DonJayamanne** [comment]
@rebornix no worries, saw the messages, and realized what it was ,

**Review by DonJayamanne — COMMENTED** [review]
please could you test this vsix on windows
I don’t think it will work, I haven’t tried it myself

Please have a look at my pr 
You might also need to copy the nodegyp files
Else the vsix will not work on windows or apple intel now will it work on Linux
It will still fallback to Jupyter and Zamboanga will not load

**Comment by DonJayamanne** [comment]
I think we can close this now
@rebornix feel free to reopen if you think we still need this.

**Pull request closed without merging**
